version: '2'
services:
  app:
    image: app:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/repo/test-results:/test-results
    command: node ./scripts/waitForDb.js && npm run test
    environment:
      - JEST_JUNIT_OUTPUT=./test-results/junit/results.xml
