# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
      
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install node v10
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | bash -
            apt-get install -y nodejs

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: start database
          command: docker-compose up --exit-code-from db
          background: true

      # run tests!
      - run:
          name: run tests
          command: |
            DB_HOST=localhost node ./scripts/waitForDb.js && npm run test

      