version: 2
jobs:
  test:
    machine:
      image: circleci/classic:201808-01
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run services
          command: |
            COMPOSE_PROJECT_NAME=cursor-based-pagination docker-compose -f ./docker-compose.yml down
            COMPOSE_PROJECT_NAME=cursor-based-pagination docker-compose -f ./docker-compose.yml up --build
          background: true
      - run:
          name: Run tests
          command: COMPOSE_PROJECT_NAME=cursor-based-pagination docker-compose -f ./docker-compose.tests.yml up --build
      - store_artifacts:
          path: ./test-results/junit
      - store_test_results:
          path: ./test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
